language: php

php:
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - vendor/bin/pest

after_success:
  - vendor/bin/php-coveralls --coverage_clover=coverage/logs/clover.xml --json_path=coverage/logs/coveralls-upload.json -v
